### ISSUE TITLE
ToB chapter change in ar4000.bcs

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#12]
see this post for problem and suggested solution
http://gibberlings3.net/forums/index.php?showtopic=29295#entry259509

**Comment by RoxanneSHS** [comment]
PR #13 submitted

**Comment by K4thos** [comment]
Roxanne, I've noticed that BG2:EE received 2.5 patch for BG2:EE, so I've done a quick update that solves all installation warnings. I'd like to discuss your pull requests and internalize them within code, but it looks like G3 is offline, so I can't view the bugs descriptions. Could you please contact me on discord? (https://discordapp.com, you don't need to download anything to open it)
K4thos#2765

**Comment by RoxanneSHS** [comment]
The bug report(s) about it are very similar. Some mod (latest example Almateria mod) adds some code to the top of the ar4000.bcs that triggers prior to the OnCreation() block that contains the chapter increment. The big OnCreation block is not executed, when you go to the bhaal plane you are still in chapter 19 (or 7 when you play without EET). 
The effect in EET is more dramatic than in non-EET game because all the dialogue and PID triggers of NPCs use the chapterGT19 LT20 barrier.
My proposal was just a safety code block that would trigger even if the first one fails. The better solution of course would be NOT to use the garbage OnCreation() trigger for the big transition block, but I think this is somehow inherited from the original code. Bioware used OnCreation() a lot, not taking into account that modders would appear some day...

**Comment by K4thos** [comment]
So this was not a bug in EET after all. Thanks for investigating the issue. OnCreation() in that block is completly usless considering there is already ```Global("TurnDay","AR4000",0)``` and ```SetGlobal("TurnDay","AR4000",1)``` in the same block. It will be removed in the RC10.
