### ISSUE TITLE
Reputation Decrease Infinite Loop

### ISSUE THREAD

**Issue by junkmonger** [K4thos/EET#16]
I couldn't find this anywhere.  I downloaded EET in March.  I'm playing through for the first time.  At the start of SOA (after transitioning from SOA) when the main character wakes up and Imoen joins, the game going into a infinite loop decreasing the group's reputation (The message is: The Party's Reputation is Decreased: -1).  The reputation is set on -1 and the game is unplayable.  The scrolling messages interfere with movement, combat and item pick ups.

Also, my editions of BG EE and BGII EE came from Steam.
[WeiDU.log](https://github.com/K4thos/EET/files/2023550/WeiDU.log)

**Comment by junkmonger** [comment]
After playing through the first floor, the bug seems to stop after meeting Sandrah by the portal north of the dryads.

**Comment by K4thos** [comment]
@junkmonger do you still have save right before transition? Please upload it. The code that adjusts reputation seems fine and I can't replicate it:
`
IF
  Global("K#FrameDelay","LOCALS",0)
  Alignment(Player1,LAWFUL_GOOD)
  ReputationGT(Player1,10)
THEN
  RESPONSE #100
    ReputationSet(10)
    Continue()
END

IF
  Global("K#FrameDelay","LOCALS",0)
  OR(2)
    Alignment(Player1,NEUTRAL_GOOD)
    Alignment(Player1,CHAOTIC_GOOD)
  ReputationGT(Player1,9)
THEN
  RESPONSE #100
    ReputationSet(9)
    Continue()
END

IF
  Global("K#FrameDelay","LOCALS",0)
  OR(3)
    Alignment(Player1,LAWFUL_NEUTRAL)
    Alignment(Player1,NEUTRAL)
    Alignment(Player1,CHAOTIC_NEUTRAL)
  ReputationGT(Player1,8)
THEN
  RESPONSE #100
    ReputationSet(8)
    Continue()
END

IF
  Global("K#FrameDelay","LOCALS",0)
  OR(2)
    Alignment(Player1,LAWFUL_EVIL)
    Alignment(Player1,NEUTRAL_EVIL)
  ReputationGT(Player1,7)
THEN
  RESPONSE #100
    ReputationSet(7)
    Continue()
END

IF
  Global("K#FrameDelay","LOCALS",0)
  Alignment(Player1,CHAOTIC_EVIL)
  ReputationGT(Player1,6)
THEN
  RESPONSE #100
    ReputationSet(6)
    Continue()
END
`

**Comment by RoxanneSHS** [comment]
CD Tweaks 1130  "Reset rep at beginning of BG2 (BGT) "  adds code to ar0602.bcs but it uses ReputationSet() and not ReputationInc() ?
Setting the global after the action e.g.
 ReputationSet(9)
    SetGlobal("CDResetRep","MYAREA",1)
may in very rare cases fail to set the global which then produces a loop - but it is very unlikely that it happens endlessly...and why would it stop when you meet Sandrah who has nothing to do with the other code?

Sandrah does nothing with Reputation nor does her presence in party decrease Rep?

There is nothing else in my very large EET installation that works on reputation in ar0602, but of course I may not have every mod.

**Comment by K4thos** [comment]
I've added pull request to CD Tweaks to disable the component on EET: https://github.com/Gibberlings3/Tweaks-Anthology/pull/10

This sounds serious so I will remove the reputation code for RC10 release. It will be likely re-introduced via RC10.1 update once I test how the transition works in patch 2.5. Better safe then sorry.
