### ISSUE TITLE
NOT INSTALLED DUE TO ERRORS EET core - resource importation

### ISSUE THREAD

**Issue by apprenticepeng** [K4thos/EET#17]
Hello,

I had a failed installation. I selected the "BWS recommended selection". 

Here's the debug message:

Uninstalled    14891 files for [EET/EET.TP2] component 0.
ERROR: Out of memory
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Automatically Skipping [EET core - resource importation] because of error.
Using Language [English]
[.\lang\en_us\dialog.tlk] created, 304680 string entries

NOT INSTALLED DUE TO ERRORS EET core - resource importation

D:\Entertainment\BG2EE>

ERROR: [Baldur.exe] -> [Baldur.exe] Patching Failed (COPY) (Out of memory)
ERROR: Out of memory
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

Without this component the installation cannot be continued.

Below is the zipped SETUP-EET.DEBUG

[SETUP-EET.zip](https://github.com/K4thos/EET/files/2126592/SETUP-EET.zip)

**Comment by K4thos** [comment]
Baldur.exe patching will be done with external LUA code to save memory in the next version, thanks for report.
