### ISSUE TITLE
EET and patch 2.5

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#18]
Here is a summary topic from recent tests and received discussions
http://baldursextendedworld.com/Vanilla_Forums/discussion/55

Main issues regarding EET
- some patches from EET core for BG2EE are no longer needed since included in vanilla
- GUI changes cause glitches for EET_GUI

**Comment by K4thos** [comment]
Thanks for the analysis. Everything mentioned in that topic (and more) is implemented locally and will be shipped with the RC10.
