### ISSUE TITLE
RC 10 Tested successfully

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#19]
I made an installation of RC10 on BG2EE v2.5. 
Everything works fine, see
http://baldursextendedworld.com/Vanilla_Forums/discussion/comment/478/#Comment_478
This was just with naked EET in the first round.
I will now do a larger modded installation but of course results will not be available too soon.

Great to have you back.

**Comment by RoxanneSHS** [comment]
Second test, done with a lot of mods, big mods and SCS.
No problem with the installation, very fast and smooth, no warnings/errors from EET at all.
The alternate SoD GUI does not work correctly, it has the issue described already by others before that the action window always reverts to the first line instead of the last.
Uninstalling the mod and going with the default GUI works.

**Comment by RoxanneSHS** [comment]
How to deal with the updated spells in patch 2.5 and resulting issues in SCS and SR (also one EET_Tweaks component) is described here under Issue 1 -Spells changed
http://baldursextendedworld.com/Vanilla_Forums/discussion/55/eet-and-patch-2-5

**Comment by K4thos** [comment]
Thanks for testing. You don't have this issue, right? https://support.baldursgate.com/issues/38182#change-222073
Thankfully it also exists in BG:EE, so it's not related to EET.

**Comment by RoxanneSHS** [comment]
No problems with cursors or screenshots. Neither in BGEE nor in BG2EE v 2,5 nor in EET - I have two versions of EET, one still on BG2EE v2.3.67 using the EET_GUI based on SoD and the other based on BG2EE v2.5 using standard GUI.
I use full screen mod always.
