### ISSUE TITLE
Can't install EET (BG1NPC conflict?)

### ISSUE THREAD

**Issue by agb1** [K4thos/EET#2]
EET installation failed at this point:

--

1461/5864 Patching compiled script file BCS/X#XZJELL.BCS...

[EET/temp/patch/BCS/X#XZJELL.BCS.BAF] PARSE ERROR at line 31 column 1-26
Near Text: ANYONE
	syntax error

[EET/temp/patch/BCS/X#XZJELL.BCS.BAF]  ERROR at line 31 column 1-26
Near Text: ANYONE
	Parsing.Parse_error
ERROR: parsing [EET/temp/patch/BCS/X#XZJELL.BCS.BAF]: Parsing.Parse_error
ERROR: [EET/temp/patch/BCS/X#XZJELL.BCS] -> [EET/temp/patch/BCS/X#XZJELL.BCS] Patching Failed (COPY) (Parsing.Parse_error)
Stopping installation because of error.
ERROR: [EET/temp/Filelist.txt] -> [EET/temp] Patching Failed (COPY) (Parsing.Parse_error)
Stopping installation because of error.

--

The file X#XZJELL.BCS is from BG1NPC Project v22.  The original BAF is x#xzjell.baf located at bg1npc\phase2\baf.  The bg1npc tp2 just compiles the baf (COMPILE EVALUATE_BUFFER ~BG1NPC/Phase2/baf/X#XZJELL.BAF~).  I do not see anything else touching the script before EET gets to it.

**Comment by agb1** [comment]
I cut most of the contents of x#xzjell.baf (kept only the first block) and rebuilt the BCS with weidu and put it in the BGEE override.  The EET installation was then able to progress past the file.

x#xzslim.bcs/.baf (in the same location in BG1NPC Project) seems to have the same issue.

**Comment by K4thos** [comment]
thanks for notification. Will take a look at it. It must be newest update for BG1NPC Project that is causing it as I've been playing with older versions without problems. It's probably related to this: http://forums.pocketplane.net/index.php?topic=29380.0

**Comment by K4thos** [comment]
newest EET package has weidu updated to 238.01, so there should no longer be problems with above linked ANYONE stuff (from weidu changelog: "WeiDU is able to resolve the IDS symbol ANYONE."). Tested with the newest BG1NPC Project available on GitHub (G3 release in not the newest): https://github.com/AstroBryGuy/BG1NPC/releases
