### ISSUE TITLE
problem with "K#DaysPassed"

### ISSUE THREAD

**Issue by repus7** [K4thos/EET#23]
I do not know much English. Therefore, I write through Google.

>IF
   !GlobalTimerNotExpired("K#TimerOneDay","GLOBAL")
THEN
   RESPONSE #100
      IncrementGlobal("K#DaysPassed","GLOBAL",1)
      SetGlobalTimer("K#TimerOneDay","GLOBAL",ONE_DAY)
      Continue()
END`

The "K#DaysPassed" counter lags behind if the travel through the world map lasts more than one day (2-3).

There is such an option:
>IF
	Global("K#SetTimerOneDay","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("K#SetTimerOneDay","GLOBAL",1)
		SetGlobalTimer("K#TimerOneDay","GLOBAL",ONE_DAY)
		Continue()
END
>
>IF
	GlobalTimerExpired("K#TimerOneDay","GLOBAL")
	Global("K#CheckDays","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("K#CheckDays","GLOBAL",1)
		SetGlobalTimer("K#TimerCheckDay","GLOBAL",1)
		Continue()
END
>
>IF
	GlobalsGT("K#TimerOneDay","K#TimerCheckDay")
	!Global("K#CheckDays","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("K#CheckDays","GLOBAL",0)
		Continue()
END
>
>IF
	GlobalsGT("K#TimerCheckDay","K#TimerOneDay")
	!Global("K#CheckDays","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("K#TimerOneDay","GLOBAL",108000) //7200*15 - ONE_DAY
		IncrementGlobal("K#DaysPassed","GLOBAL",1)
END

**Comment by K4thos** [comment]
you're right, thank you. Your code has been implemented.

**Comment by repus7** [comment]
With this code you need to fix k#telbgt.bcs

**Comment by repus7** [comment]
With this code you need to fix k#telbgt.bcs

>SetGlobal("K#temp","GLOBAL",29)
    AdvanceTime(ONE_MONTH)
    AddGlobals("K#DaysPassed","K#temp")

>SetGlobal("K#temp","GLOBAL",29)
    AdvanceTime(ONE_MONTH)
    AddGlobals("K#DaysPassed","K#temp")
    IncrementGlobal("K#TimerOneDay","GLOBAL",3132000)
    
    Or simply
    
>AdvanceTime(ONE_MONTH)

With AdvanceTime, there are no problems. But if you change K#DaysPassed manually, the counter will go ahead for 29 days, because Timer K#TimerOneDay will greatly lag behind timer K#TimerCheckDay.
