### ISSUE TITLE
BGEE/SoD patch 2.5 finding

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#25]
Maybe this finding helps:
The EET failures witch patch 2.5 only seem to appear with the official release. I had no issues with testing it on the Beta pre-release 2.5.10. EET installs without error with this one.
Maybe this can narrow down your research. I cannot test the current release, still waiting for my update.

**Comment by K4thos** [comment]
Thanks. RC11 supports the latest patch.
