### ISSUE TITLE
Errors with RC11

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#26]
I received those two errors during resource importation
- CButt.bam  >>> I copied existing BGEE CBut,bam to CButt,bam into BGEE/override
- BPEnda.2da >>> I copied existing BGEE BPend.2da to BPenda,2da into BGEE/override

After my manipulation, EET and EET_end ran without error.

I used v 2.3.67.3 and 2,5,10 beta for the attempts (my 2.5.17 download fails each time), so ignore this if it is a version issue and RC11 only works with the latest version.

**Comment by RoxanneSHS** [comment]
Here is another user's report about the issue http://baldursextendedworld.com/Vanilla_Forums/discussion/91/eet-installation-error

**Comment by K4thos** [comment]
it works only with 2.5.17. There are massive changes with resources compared to beta - Beamdog recreated all biff files for the stable release. Unless you can reproduce the issue on one of stable releases (which would mean resource differences between Beamdog launcher verion and Steam release etc,) this is not really an issue.

**Comment by RoxanneSHS** [comment]
Confirmed. The files exist in the 2.5.17 update. The issue and reports are relevant only for the interim until all users have received their update. This means that those trying to install EET RC11 with earlier BGEE versions have the problem and it will go away over time when all have made the transition.
Maybe something worth to publish somehow to avoid questions?

**Comment by cleverestx** [comment]
I wanted to thank you for both posting this here. It helped me figure out why my EET patching was failing. I was at version 2.5.16.6 and not 2.5.17. I believe when I get this updated it will resolve the issue but will post if not. Thanks again.
