### ISSUE TITLE
Compatibility Murneth

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#27]
The mod as of v12 is EET compatible now and can be removed from the BG1 importation.
Tested it with murneth v12 on EET RC11
Works directly on BG2EE after EET now.

**Comment by RoxanneSHS** [comment]
The same is now applicable for Vynd v2

Both mods could be removed from the EET importation of BGEE. But I understand that if they stay it will just do nothing if they are not found in the BGEE-Weidu.log when EET runs.

**Comment by K4thos** [comment]
thanks!
