### ISSUE TITLE
immediate error running setup with latest build

### ISSUE THREAD

**Issue by agb1** [K4thos/EET#3]
WeiDU v 23800 Log

 Setup-EET.exe --no-exit-pause --noautoupdate --language 0 --skip-at-view --quick-log --args-list p C:\Users\ggoldman\test\BGEE --force-install-list 0 --logapp
[./chitin.key] loaded, 847192 bytes
[./chitin.key] 186 BIFFs, 60118 resources
[./goglog.ini] loaded, 1099 bytes
[.\weidu.conf] loaded, 16 bytes
[.\lang\en_us/dialog.tlk] loaded, 11589335 bytes
[.\lang\en_us/dialog.tlk] 103044 string entries

[EET/EET.TP2] PARSE ERROR at line 1823 column 1-61
Near Text: ~%USER_DIRECTORY%/characters~
	GLR parse error

[EET/EET.TP2]  ERROR at line 1823 column 1-61
Near Text: ~%USER_DIRECTORY%/characters~
	Parsing.Parse_error
ERROR: parsing [EET/EET.TP2]: Parsing.Parse_error
ERROR: problem parsing TP file [EET/EET.TP2]: Parsing.Parse_error

FATAL ERROR: Parsing.Parse_error

---

The problematic lines are these:

ACTION_IF (NOT DIRECTORY_EXISTS ~%USER_DIRECTORY%/characters~) BEGIN
	MKDIR ~%USER_DIRECTORY%/characters~
END

If I comment them out, the install proceeds.

**Comment by K4thos** [comment]
did you use older weidu for this installation? DIRECTORY_EXISTS is a new command introduced in Weidu beta 238.01. The exe file included in this package should be the newest version so unless GitHub failed to update this file this shouldn't be the case. Will try to reupload setup-EET.exe

**Comment by ALIENQuake** [comment]
@agb1 It's because BWS use weidu 238.0 not 238.01, wisp must provide direct link to exe.
