### ISSUE TITLE
item_use.2da

### ISSUE THREAD

**Issue by repus7** [K4thos/EET#31]
in bg2_2DA.tph:
col4 = Flags
col5 = Username (StrRef)

<2DA V1.0
*
           USER       STRREF     FLAG       USERNAME   
MISC84     MINSC      10218      3          9501       
MISC88     ALORA      10219      1          270        
MISC89     EDWIN      10222      1          271        
SW1H13     XAN        10220      2          268        
AROW14     ELDOTH     10221      2          6254       
NPARM      JAN        9382       2          8652       
NPCHAN     VALYGAR    9382       2          9158       
NPCLCK     CERND      9382       2          9153       
NPMISC1    JAN        9382       2          8652...>

**Comment by K4thos** [comment]
fixed, thanks!
