### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by AngeloMaligno** [K4thos/EET#34]
Here's what I got when I tried to install.

ERROR Installing [EET core - resource importation], rolling back to previous state

Will uninstall 4 files for [EET/EET.TP2] component 0
Uninstalled 4 files for [EET/EET.TP2] component 0
ERROR: Unix.Unix_error(20, "stat", "EET/temp/biff/CBUTT.BAM")

**Comment by K4thos** [comment]
you likely don't have latest patch downloaded. If you're using GOG you need to download whole installator, not incremental patch - GOG only distributes patch for BG1, not SoD.
