### ISSUE TITLE
Dynamically compiled version of lua doesn't match system libraries

### ISSUE THREAD

**Issue by AngelGryph** [K4thos/EET#37]
The Unix version of lua shipped with EET is dynamically compiled and thus will fail on systems that don't have the same library versions (in my case, my system has version 7 of readline but the lua version shipped with EET is compiled against version 6).

I recommend shipping a statically compiled version and/or using the system version of lua if present.

**Comment by K4thos** [comment]
@AngelGryph, could you please upload this statically compiled version of unix binary?

**Comment by AngelGryph** [comment]
I don't have one ready (I got around the issue by just copying in my system's version of lua, which is also dynamic), but I can probably make one.  I will look into it tonight.

**Comment by AngelGryph** [comment]
Well, it took a bit of fiddling but here you go.  I did a quick check on the other binaries there (weidu and ffmpeg), they are already statically compiled versions.  Pull request is ready for you.

**Comment by K4thos** [comment]
thanks!
