### ISSUE TITLE
Cant install EET

### ISSUE THREAD

**Issue by peteradwyer** [K4thos/EET#42]
ERROR: [EET/SOD_GUI/CH01AJON.MOS] -> [EET/SOD_GUI] Patching Failed (COPY) (Unix.Unix_error(20, "stat", "EET/temp/biff/mos1347.pvrz"))
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Will uninstall 159 files for [EET/EET.TP2] component 0.
Uninstalled    159 files for [EET/EET.TP2] component 0.
ERROR: Unix.Unix_error(20, "stat", "EET/temp/biff/mos1347.pvrz")
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Automatically Skipping [EET core (resource importation)] because of error.
Using Language [English]

NOT INSTALLED DUE TO ERRORS EET core (resource importation)

C:\Program Files (x86)\Steam\steamapps\common\Baldur's Gate II Enhanced Edition>
ERROR: [EET/SOD_GUI/CH01AJON.MOS] -> [EET/SOD_GUI] Patching Failed (COPY) (Unix.Unix_error(20, "stat", "EET/temp/biff/mos1347.pvrz"))
ERROR: Unix.Unix_error(20, "stat", "EET/temp/biff/mos1347.pvrz")
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

Without this component the installation cannot be continued.

**Comment by TeskalFlink** [comment]
This error may happen, because the SOD DLC is not merged. Looks like Project Infinity did deinstall the SOD DLC merge. After merging it again, issue was solved.

**Comment by K4thos** [comment]
thanks!

**Comment by ALIENQuake** [comment]
@TeskalFlink Nope, Project Infinity doesn't uninstall any mods on its own, unless you use 'Uninstall all mods' feature.

**Comment by TeskalFlink** [comment]
> unless you use 'Uninstall all mods' feature.

Yupp, I'm sure this was it. 
This issue was solved after merging the SOD into a DLC again. To be sure, I have DlcMerger in my load order at the very beginning.
