### ISSUE TITLE
Invalid BG:EE directory, or incorrect BG:EE installation

### ISSUE THREAD

**Issue by HeartOfGold1337** [K4thos/EET#5]
Hello,
I have installed the latest version of Baldur's Gate Enhanced Edition and Baldur's Gate II Enhanced Edition from steam. I did not install any mods.
I downloaded the newest EET version and tried to install it. I moved all files of the mod to my Baldur's Gate II Enhanced Edition directory at C:\Program Files\Steam\SteamApps\common\Baldur's Gate II Enhanced Edition (EET (folder), .gitattributes, .gitignore, README.md, setup-EET.exe).
I then ran the setup-EET.exe.
"0" english
"n" no readme
"i" install
C:\Program Files\Steam\SteamApps\common\Baldur's Gate Enhanced Edition  --> for my full path to my BG:EE installation.
I then get the message:
Invalid BG:EE directory, or incorrect BG:EE installation.
It is safe to abort this installation by closing this window or pressing Ctrl+C.

Can you please help me?
Kind regards,
HeartOfGold1337

**Comment by Silvery-Corgan** [comment]
@HeartOfGold1337 Please install Steam in another folder, preferrably not on the C drive and definitely not in Program Files. The issue here is with the Program Files directory which has special permissions given by Windows.

So a fist step would be to uninstall Steam and all Steam Games that you have and install it on a different folder (like C:\Games\Steam\) or preferably on a different drive altogether (like D:\Steam\) and see if the issue persists.

**Comment by HeartOfGold1337** [comment]
@Silvery-Corgan Thank you for your fast reply!
I'll go reinstall then.. :D

**Comment by HeartOfGold1337** [comment]
@Silvery-Corgan Thank you for your fast reply!

I reinstalled steam in C:\Steam.
I moved my Baldurs Gate to C:\Steam\steamapps\common\Baldur's Gate Enhanced Edition.
I only did copy paste. I did not download Baldurs gate again (can that be a problem?)

It still does not work.

**Comment by Silvery-Corgan** [comment]
@HeartOfGold1337 Copying the folder should not introduce problems. Just make sure that you own the folder C:\Steam and that you have full permissions recursively (that means everything inside that folder including its subfolders are under your ownership)

If the issue persists then it might just be a bug.

**Comment by HeartOfGold1337** [comment]
@Silvery-Corgan yep, still not working :-/

**Comment by r-e-d** [comment]
@HeartOfGold1337, do you have Siege of Dragonspear ? It is required for EET.

Also, for the Steam (and GoG) version, you must use [modmerge](https://forums.beamdog.com/discussion/50441/modmerge-merge-your-steam-gog-zip-based-dlc-into-something-weidu-nearinfinity-dltcep-can-use) before installing.

**Comment by HeartOfGold1337** [comment]
I did not have Siege of Dragonspear...
Downloading it now. I expect it to be working afterwards. Thanks for your help.
