### ISSUE TITLE
Cannot install EET core

### ISSUE THREAD

**Issue by TheGoldenMeme** [K4thos/EET#50]
This is what was found in my debug: 

WeiDU v 24600 Log

 C:\Program Files (x86)\Steam\steamapps\common\Baldur's Gate II Enhanced Edition\setup-EET.exe
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\engine.lua] loaded, 104 bytes
[.\weidu.conf] loaded, 17 bytes
[.\lang\en_us\dialog.tlk] loaded, 11630279 bytes
[.\lang\en_us\dialog.tlk] 103241 string entries
WARNING: parsing log [WeiDU.log]: Sys_error("WeiDU.log: No such file or directory")

Choose your language:
 0 [English]
 1 [Polski (Polish)]
 2 [Spanish]
Using Language [English]
[English] has 6 top-level TRA files
[EET/lang/en_US/prompts.tra] has 56 translation strings
[EET/lang/en_US/setup.tra] has 14 translation strings
[EET/lang/en_US/chapters.tra] has 95 translation strings
[EET/lang/en_US/dialog.tra] has 37 translation strings
[EET/lang/en_US/2da.tra] has 55 translation strings
[EET/lang/en_US/compatibility.tra] has 11 translation strings

Using .\lang\en_us\dialog.tlk

Would you like to display the readme? [Y]es [N]o

Install Component [EET core (resource importation)]?
[I]nstall, or [N]ot Install or [Q]uit? 
Installing [EET core (resource importation)] [1.0 RC12]

INTERACTIVE = 1

LANGUAGE = en_US

argv[0] = %argv[0]%

argv[1] = %argv[1]%
Copying and patching 1 file ...
[weidu.conf] loaded, 17 bytes

LANGUAGE_BG2 = en_US
Creating 1 directory
Copying 1 file ...
Copying and patching 2 files ...
[EET/other/cpmvars/eet_cpmvars.tpa] loaded, 59981 bytes
[EET/other/EET_functions.tph] loaded, 43945 bytes
Copying and patching 1 file ...
Copied [.../programfiles.bat] to [EET/temp/programfiles.bat] (NO BACKUP MADE!)
Copying and patching 1 file ...
[EET/temp/programfiles.txt] loaded, 24 bytes
Copied [EET/temp/programfiles.txt] to [EET/temp/programfiles.txt] (NO BACKUP MADE!)

Detected BG:EE directory as C:\Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition.
Is this correct? [Y]es or [N]o
User answer: "y"

C:\Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition directory assigned to default dir
Copying and patching 1 file ...
Copied [.../bgee_dir.txt] to [EET/bgee_dir.txt] (NO BACKUP MADE!)
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/weidu.conf] loaded, 16 bytes

LANGUAGE_BG1 = en_US
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] loaded, 15088 bytes
Copied [C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] to [WeiDU-BGEE.log]
Copying 1 file ...
Copied [.../arch_var.bat] to [arch_var.bat]
[arch_var.txt] loaded, 8 bytes

arch_var = x86_64\

lua assigned to EET\bin\win32\x86_64\lua.exe

ffmpeg assigned to EET\bin\win32\ffmpeg.exe

weidu assigned to EET\bin\win32\x86_64\weidu.exe
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] loaded, 15088 bytes
FAILURE:
You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation).
ERROR: [C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] -> [EET/temp] Patching Failed (COPY) (Failure("You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation)."))
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Unable to Unlink [EET/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "EET/backup/0/OTHER.0")
[EET/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   2 files for [EET/EET.TP2] component 0.
Uninstalled      2 files for [EET/EET.TP2] component 0.
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
Unable to Unlink [EET/backup/0/READLN.0]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0")
Unable to Unlink [EET/backup/0/READLN.0.TEXT]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0.TEXT")
ERROR: Failure("You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation).")
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Using Language [English]
[English] has 6 top-level TRA files
[EET/lang/en_US/prompts.tra] has 56 translation strings
[EET/lang/en_US/setup.tra] has 14 translation strings
[EET/lang/en_US/chapters.tra] has 95 translation strings
[EET/lang/en_US/dialog.tra] has 37 translation strings
[EET/lang/en_US/2da.tra] has 55 translation strings
[EET/lang/en_US/compatibility.tra] has 11 translation strings

Install Component [EET core (resource importation)]?
[I]nstall, or [N]ot Install or [Q]uit? 
Installing [EET core (resource importation)] [1.0 RC12]

INTERACTIVE = 1

LANGUAGE = en_US

argv[0] = %argv[0]%

argv[1] = %argv[1]%
Copying and patching 1 file ...
[weidu.conf] loaded, 17 bytes

LANGUAGE_BG2 = en_US
Creating 1 directory
Copying 1 file ...
Copying and patching 2 files ...
[EET/other/cpmvars/eet_cpmvars.tpa] loaded, 59981 bytes
[EET/other/EET_functions.tph] loaded, 43945 bytes
Copying and patching 1 file ...
[EET/bgee_dir.txt] loaded, 76 bytes

C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition directory assigned via EET/bgee_dir.txt
Copying and patching 1 file ...
Copied [.../bgee_dir.txt] to [EET/bgee_dir.txt] (NO BACKUP MADE!)
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/weidu.conf] loaded, 16 bytes

LANGUAGE_BG1 = en_US
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] loaded, 15088 bytes
Copied [C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] to [WeiDU-BGEE.log]
Copying 1 file ...
Copied [.../arch_var.bat] to [arch_var.bat]
[arch_var.txt] loaded, 8 bytes

arch_var = x86_64\

lua assigned to EET\bin\win32\x86_64\lua.exe

ffmpeg assigned to EET\bin\win32\ffmpeg.exe

weidu assigned to EET\bin\win32\x86_64\weidu.exe
Copying and patching 1 file ...
[C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] loaded, 15088 bytes
FAILURE:
You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation).
ERROR: [C:/Program Files (x86)/Steam/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] -> [EET/temp] Patching Failed (COPY) (Failure("You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation)."))
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Unable to Unlink [EET/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "EET/backup/0/OTHER.0")
[EET/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   2 files for [EET/EET.TP2] component 0.
Uninstalled      2 files for [EET/EET.TP2] component 0.
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
Unable to Unlink [EET/backup/0/READLN.0]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0")
Unable to Unlink [EET/backup/0/READLN.0.TEXT]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0.TEXT")
ERROR: Failure("You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation).")
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Using Language [English]
[English] has 6 top-level TRA files
[EET/lang/en_US/prompts.tra] has 56 translation strings
[EET/lang/en_US/setup.tra] has 14 translation strings
[EET/lang/en_US/chapters.tra] has 95 translation strings
[EET/lang/en_US/dialog.tra] has 37 translation strings
[EET/lang/en_US/2da.tra] has 55 translation strings
[EET/lang/en_US/compatibility.tra] has 11 translation strings

Install Component [EET core (resource importation)]?
[I]nstall, or [N]ot Install or [Q]uit? 
Skipping [EET core (resource importation)]
Saving This Log:

NOT INSTALLED DUE TO ERRORS EET core (resource importation)

		WeiDU Timings
OUTER_INNER_PATCH_SAVE           0.000
parsing .tra files               0.000
<<<<<<<<                         0.000
OUTER_WHILE                      0.000
ACTION_FOR_EACH                  0.000
ACTION_MATCH                     0.000
adding translation strings       0.000
DELETE                           0.000
load TLK                         0.000
DEFINE_PATCH_FUNCTION            0.000
ACTION_READLN                    0.000
DEFINE_ACTION_FUNCTION           0.000
OUTER_SET                        0.000
INCLUDE                          0.000
BUT_ONLY                         0.000
MKDIR                            0.000
ACTION_DEFINE_ASSOCIATIVE_ARRAY   0.000
ACTION_PHP_EACH                  0.000
AT_NOW                           0.000
AT_EXIT                          0.000
function overhead                0.000
DEFINE_ACTION_MACRO              0.000
OUTER_INNER_PATCH                0.000
ACTION_IF                        0.000
PRINT                            0.000
READ_*                           0.000
LAUNCH_ACTION_FUNCTION           0.000
saving files                     0.000
DEFINE_PATCH_MACRO               0.000
COPY                             0.000
tp2 uninstall                    0.016
OUTER_SPRINT                     0.016
eval_pe                          0.016
Parsing TP2 files                0.078
loading files                    0.094
stuff not covered elsewhere      0.094
unmarshal TLK                    0.234
Parsing TPA files                0.266
process_patch2                   0.734
unmarshal KEY                   18.547
TOTAL                           20.094
Executing: [rmdir /s /q EET\temp]

**Comment by CrevsDaak** [comment]
> FAILURE:
> You've installed wrong The Stone of Askavar component. EET is compatible with Default version (option 1 during installation).

This is way too self explanatory.
