### ISSUE TITLE
Dynaheir Minsc appearing in camp BD1000

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#55]
Current conditions
Global("bd_move_minsc","bd1000",0) 
!Dead("minsc")  // Minsc
!InPartyAllowDead("minsc")  

should be changed to
	Global("bd_move_minsc","bd1000",0) 
	GlobalLT("Chapter","GLOBAL",13)
	!StateCheck("Minsc",STATE_REALLY_DEAD)
	!StateCheck("Dynaheir",STATE_REALLY_DEAD) 

And the same for 
Global("bd_move_dyna","bd1000",0)
in the next code block

Minsc or Dynaheir do not appear in SoD if one of them died before (see BD0108.bcs) however they may spawn, even if one of them is dead, later in the first out of city camp.

**Comment by K4thos** [comment]
fixed, thanks
