### ISSUE TITLE
ERROR: preprocessing APPEND_EARLY [EET/compile/d/cleansod.d]: Failure("resource [BDDEEP.DLG] not found for 'ADD_TRANS_TRIGGER'")

### ISSUE THREAD

**Issue by CytrynianSodu** [K4thos/EET#8]
Mam taki błąd  na linuxie
Installing DLG files...
Copying and patching 1 file ...
Compiling 1819 dialogue files ...

[action list near line 39, column 2 of EET/temp/patch/d/menda4.d] PARSE WARNING at line 39 column 1-56
Near Text: )
	[ApplySpell] argument [BERESH_CHANGE] not found in [Spell.IDS]

[action list near line 65, column 2 of EET/temp/patch/d/menda4.d] PARSE WARNING at line 65 column 1-56
Near Text: )
	[ApplySpell] argument [BERESH_CHANGE] not found in [Spell.IDS]

ERROR locating resource for 'ADD_TRANS_TRIGGER'
Resource [BDDEEP.DLG] not found in KEY file:
	[./chitin.key]
ERROR: preprocessing APPEND_EARLY [EET/compile/d/cleansod.d]: Failure("resource [BDDEEP.DLG] not found for 'ADD_TRANS_TRIGGER'")
Stopping installation because of error.

BLAD podczas instalacji [Core EET (game importation)], powrot do poprzedniego stanu
Will uninstall 9987 files for [EET_CORE.TP2] component 0.
Uninstalled    9987 files for [EET_CORE.TP2] component 0.
ERROR: Failure("resource [BDDEEP.DLG] not found for 'ADD_TRANS_TRIGGER'")
PROSZE, wyslij plik SETUP-EET_CORE.DEBUG do K4thos (swit)
Automatically Skipping [Core EET (game importation)] because of error.
Using Language [Polski (Polish)]
[./lang/en_us/dialog.tlk] created, 271377 string entries
[./lang/en_us/dialogf.tlk] created, 271377 string entries

NIE ZAINSTALOWANO Z POWODU BLEDOW Core EET (game importation)

[setup-eet_core.debug.zip](https://github.com/K4thos/EET/files/722030/setup-eet_core.debug.zip)

**Comment by K4thos** [comment]
http://gibberlings3.net/forums/index.php?showtopic=28527&hl=
