### ISSUE TITLE
Issue with directory path on macOS

### ISSUE THREAD

**Issue by orcutt989** [K4thos/EET#9]
OS: macOS Sierra 10.12.6
Game versions: Steam BGEE+SoD & BG2EE installed to their default Steam locations

I receive the following error when trying to execute EET.tp2 with the following methods.

1. Your included weidu-osx
     _weidu-osx EET.tp2_
2. Weidu 2.42 http://www.weidu.org/~thebigg/
     _weidu eet/EET.tp2_
3. Weidu macOS wrapper https://github.com/subtledoctor/OS-X-Weidu-Launcher/releases 

_Enter the full path to your BG:EE+SoD installation then press Enter.
Example: C:\Program Files (x86)\BeamDog\Games\00806_
**/Users/username/Library/Application\ Support/Steam/steamapps/common/Baldur\'s\ Gate\ 
Enhanced\ Edition**
_Invalid directory, or incorrect BG:EE+SoD installation._

It appears as if your file does not like the path **/Users/username/Library/Application\ Support/Steam/steamapps/common/Baldur\'s\ Gate\ 
Enhanced\ Edition**.

I have also tried putting it in quotes and it also does not work.

Thanks in advance!

**Comment by kaikiai** [comment]
On Windows there is "Mod Merge" needed for Steam, I think this will be needed for Mac too, or am I wrong here @K4thos? 
https://github.com/ScottBrooks/modmerge

**Comment by orcutt989** [comment]
I installed modmerge already - it exists for macOS.

**Comment by Argent77** [comment]
Have you tried entering the path without escaped spaces?
```
/Users/username/Library/Application Support/Steam/steamapps/common/Baldur's Gate Enhanced Edition
```

**Comment by ThyWoof** [comment]
You should enter the path all the way to the Resources folder where chitin.key is:

/Users/username/Library/Application\ Support/Steam/steamapps/common/Baldur's\ Gate\
Enhanced\ Edition/Contents/Resources

**Comment by K4thos** [comment]
Path mentioned by ThyWoof has been added to default BG:EE paths pool, thanks. As Argent77 mentioned escape spaces are not needed.

**Comment by orcutt989** [comment]
Sorry about the delay, but I tried ThyWoof's path and it still doesnt work. `chitin.key` is in `/Users/username/Library/Application\ Support/Steam/steamapps/common/Baldur's\ Gate
Enhanced\ Edition`
